; Auto-generated by Jetski Course Editor.
; z88dk-z80asm compatible output.
; Layout per segment: curve(defb), length(defw), flags(defb)
; Index entry: name_ptr(defw), difficulty(defb), segment_count(defw), segments_ptr(defw)

SECTION rodata_user
PUBLIC course_index
PUBLIC course_index_count

the_lagoon_name:
    defm "The_Lagoon",0

the_lagoon_segments:
    defb $00
    defw $2710
    defb $10
    defb $23
    defw $1388
    defb $00
    defb $1c
    defw $03e8
    defb $01
    defb $19
    defw $05dc
    defb $00
    defb $00
    defw $0dac
    defb $00
    defb $f3
    defw $01f4
    defb $04
    defb $e7
    defw $09c4
    defb $02
    defb $33
    defw $1f40
    defb $01
    defb $00
    defw $0dac
    defb $03
    defb $34
    defw $1f40
    defb $00
    defb $00
    defw $125c
    defb $01
    defb $1a
    defw $09c4
    defb $20
    defb $00
    defw $01f4
    defb $00
    defb $1a
    defw $0dac
    defb $00

the_river_name:
    defm "The_River",0

the_river_segments:
    defb $00
    defw $7530
    defb $31

zig_zag_alley_name:
    defm "Zig_Zag_Alley",0

zig_zag_alley_segments:
    defb $00
    defw $0dac
    defb $20
    defb $65
    defw $1f40
    defb $01
    defb $9b
    defw $1f40
    defb $01
    defb $65
    defw $1f40
    defb $04
    defb $9a
    defw $1f40
    defb $02
    defb $00
    defw $1388
    defb $08
    defb $ce
    defw $1388
    defb $01
    defb $00
    defw $1f40
    defb $00
    defb $32
    defw $1388
    defb $01
    defb $9c
    defw $2ee0
    defb $02
    defb $00
    defw $2ee0
    defb $14

course_index:
    defw the_lagoon_name
    defb $01
    defw $000e
    defw the_lagoon_segments
    defw the_river_name
    defb $04
    defw $0001
    defw the_river_segments
    defw zig_zag_alley_name
    defb $03
    defw $000b
    defw zig_zag_alley_segments

course_index_count:
    defw $0003
