/* Auto-generated by Jetski Course Editor. */
#include <stdint.h>

typedef struct {
    int8_t curve;
    uint16_t length;
    uint8_t flags;
} TrackSegment;

typedef struct {
    const char *name;
    uint8_t difficulty;
    uint16_t segment_count;
    const TrackSegment *segments;
} CourseIndexEntry;

static const char the_lagoon_name[] = "The_Lagoon";
static const TrackSegment the_lagoon_segments[] = {
    { (int8_t)0, (uint16_t)10000, (uint8_t)0x10 },
    { (int8_t)35, (uint16_t)5000, (uint8_t)0x00 },
    { (int8_t)28, (uint16_t)1000, (uint8_t)0x01 },
    { (int8_t)25, (uint16_t)1500, (uint8_t)0x00 },
    { (int8_t)0, (uint16_t)3500, (uint8_t)0x00 },
    { (int8_t)-13, (uint16_t)500, (uint8_t)0x04 },
    { (int8_t)-25, (uint16_t)2500, (uint8_t)0x02 },
    { (int8_t)51, (uint16_t)8000, (uint8_t)0x01 },
    { (int8_t)0, (uint16_t)3500, (uint8_t)0x03 },
    { (int8_t)52, (uint16_t)8000, (uint8_t)0x00 },
    { (int8_t)0, (uint16_t)4700, (uint8_t)0x01 },
    { (int8_t)26, (uint16_t)2500, (uint8_t)0x20 },
    { (int8_t)0, (uint16_t)500, (uint8_t)0x00 },
    { (int8_t)26, (uint16_t)3500, (uint8_t)0x00 },
};

static const char the_river_name[] = "The_River";
static const TrackSegment the_river_segments[] = {
    { (int8_t)0, (uint16_t)30000, (uint8_t)0x31 },
};

static const char zig_zag_alley_name[] = "Zig_Zag_Alley";
static const TrackSegment zig_zag_alley_segments[] = {
    { (int8_t)0, (uint16_t)3500, (uint8_t)0x20 },
    { (int8_t)101, (uint16_t)8000, (uint8_t)0x01 },
    { (int8_t)-101, (uint16_t)8000, (uint8_t)0x01 },
    { (int8_t)101, (uint16_t)8000, (uint8_t)0x04 },
    { (int8_t)-102, (uint16_t)8000, (uint8_t)0x02 },
    { (int8_t)0, (uint16_t)5000, (uint8_t)0x08 },
    { (int8_t)-50, (uint16_t)5000, (uint8_t)0x01 },
    { (int8_t)0, (uint16_t)8000, (uint8_t)0x00 },
    { (int8_t)50, (uint16_t)5000, (uint8_t)0x01 },
    { (int8_t)-100, (uint16_t)12000, (uint8_t)0x02 },
    { (int8_t)0, (uint16_t)12000, (uint8_t)0x14 },
};

const CourseIndexEntry g_course_index[] = {
    { the_lagoon_name, (uint8_t)1, (uint16_t)14, the_lagoon_segments },
    { the_river_name, (uint8_t)4, (uint16_t)1, the_river_segments },
    { zig_zag_alley_name, (uint8_t)3, (uint16_t)11, zig_zag_alley_segments },
};

const uint16_t g_course_index_count =
    (uint16_t)(sizeof(g_course_index) / sizeof(g_course_index[0]));
